export const landingSectionData = [{
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topline: "Top Line",
  headline: "headline",
  description: "description",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "img/svg3.svg",
  alt: "alt text",
  dark: true,
  primary: true,
  darkText: false
},
{
  id: "services",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topline: "Top Line",
  headline: "headline",
  description: "description",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "img/svg1.svg",
  alt: "alt text",
  dark: false,
  primary: false,
  darkText: true
},
]